server:
  port: 8084
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo
          uri: lb://eureka-provider
          predicates:
            - Path=/
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/