server:
  port: 8081
spring:
  application:
    name: eureka-provider
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
info:
  name: ${spring.application.name}
  host: ${eureka.instance.hostname}
  port: ${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'
---
spring:
  config:
    activate:
      on-profile: cluster1
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/
---
spring:
  config:
    activate:
      on-profile: cluster2
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/
---
spring:
  config:
    activate:
      on-profile: cluster3
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/,http://server3:8763/eureka/
